# Generated by Django 5.1.6 on 2025-03-02 07:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='url_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterModelTable(
            name='note',
            table='notes',
        ),
    ]
