# Generated by Django 5.1.6 on 2025-03-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_id_alter_note_url_id_alter_note_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='url_id',
            field=models.TextField(max_length=255, unique=True),
        ),
    ]
