# Generated by Django 5.1.6 on 2025-03-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='file',
        ),
    ]
