# Generated by Django 4.2.28 on 2026-02-06 18:19

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_note_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-last_accessed'], 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AddField(
            model_name='note',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft deletion flag'),
        ),
        migrations.AddField(
            model_name='note',
            name='last_accessed',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, help_text='Timestamp when note was last accessed (for auto-deletion)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when note was last modified'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Text content of the note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when note was created'),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the note', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='url_id',
            field=models.CharField(db_index=True, help_text='URL-safe identifier for accessing the note', max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['url_id', 'is_deleted'], name='notes_url_id_09e27e_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['last_accessed', 'is_deleted'], name='notes_last_ac_69bee7_idx'),
        ),
    ]
